### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by whernandez0989** [nikazooz/laravel-simplesheet-docs#1]
Hi, error with laravel 8,

  Problem 1
    - Root composer.json requires nikazooz/laravel-simplesheet ^1.2 -> satisfiable by nikazooz/laravel-simplesheet[1.2.0].
    - nikazooz/laravel-simplesheet 1.2.0 requires box/spout ^2.7 -> found box/spout[v2.7.0, v2.7.1, v2.7.2, v2.7.3] but it conflicts with your root composer.json require (^3.2).

**Comment by nikazooz** [comment]
Hey :wave:
Not really a documentation issue so I'll close it here and respond in the package repo
